// <auto-generated />
using DDDInPractice.Logic.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DDDInPractice.Logic.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220602082143_CreateSnackAndSlotTables")]
    partial class CreateSnackAndSlotTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DDDInPractice.Logic.Slot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<long>("SnackMachineId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SnackMachineId");

                    b.ToTable("Slot");
                });

            modelBuilder.Entity("DDDInPractice.Logic.Snack", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Snack");
                });

            modelBuilder.Entity("DDDInPractice.Logic.SnackMachine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"), 1L, 1);

                    b.HasKey("Id");

                    b.ToTable("SnackMachine");
                });

            modelBuilder.Entity("DDDInPractice.Logic.Slot", b =>
                {
                    b.HasOne("DDDInPractice.Logic.SnackMachine", "SnackMachine")
                        .WithMany("Slots")
                        .HasForeignKey("SnackMachineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DDDInPractice.Logic.SnackPile", "SnackPile", b1 =>
                        {
                            b1.Property<long>("SlotId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("Price");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int")
                                .HasColumnName("Quantity");

                            b1.Property<long>("SnackId")
                                .HasColumnType("bigint");

                            b1.HasKey("SlotId");

                            b1.HasIndex("SnackId")
                                .IsUnique();

                            b1.ToTable("Slot");

                            b1.WithOwner()
                                .HasForeignKey("SlotId");

                            b1.HasOne("DDDInPractice.Logic.Snack", "Snack")
                                .WithOne()
                                .HasForeignKey("DDDInPractice.Logic.SnackPile", "SnackId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Snack");
                        });

                    b.Navigation("SnackMachine");

                    b.Navigation("SnackPile")
                        .IsRequired();
                });

            modelBuilder.Entity("DDDInPractice.Logic.SnackMachine", b =>
                {
                    b.OwnsOne("DDDInPractice.Logic.Money", "MoneyInside", b1 =>
                        {
                            b1.Property<long>("SnackMachineId")
                                .HasColumnType("bigint");

                            b1.Property<int>("FiveDollarCount")
                                .HasColumnType("int")
                                .HasColumnName("FiveDollarCount");

                            b1.Property<int>("OneCentCount")
                                .HasColumnType("int")
                                .HasColumnName("OneCentCount");

                            b1.Property<int>("OneDollarCount")
                                .HasColumnType("int")
                                .HasColumnName("OneDollarCount");

                            b1.Property<int>("QuarterCount")
                                .HasColumnType("int")
                                .HasColumnName("QuarterCount");

                            b1.Property<int>("TenCentCount")
                                .HasColumnType("int")
                                .HasColumnName("TenCentCount");

                            b1.Property<int>("TwentyDollarCount")
                                .HasColumnType("int")
                                .HasColumnName("TwentyDollarCount");

                            b1.HasKey("SnackMachineId");

                            b1.ToTable("SnackMachine");

                            b1.WithOwner()
                                .HasForeignKey("SnackMachineId");
                        });

                    b.Navigation("MoneyInside")
                        .IsRequired();
                });

            modelBuilder.Entity("DDDInPractice.Logic.SnackMachine", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
